server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauth2?serverTimezone=UTC&useSSL=false
    username: oauth2
    password: 1324
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    #show-sql: true
    properties:
      hibernate.format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            scope:
              - email
              - profile

          facebook:
            client-id:
            client-secret:
            scope:
              - email
              - public_profile

          naver:
            client-id:
            client-secret:
            scope:
              - email
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            client-name: Naver

          kakao:
            client-id:
            client-secret:
            scope:
              - account_email
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-name: Kakao
            client-authentication-method: POST

        provider:
          naver:
            authorization-uri:  https://nid.naver.com/oauth2.0/authorize
            token-uri:  https://nid.naver.com/oauth2.0/token
            user-info-uri:  https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri:  https://kauth.kakao.com/oauth/authorize
            token-uri:  https://kauth.kakao.com/oauth/token
            user-info-uri:  https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

